#!/usr/bin/env python3
"""Create an isolated teaching style preview from an explicit main-repo revision."""
import argparse
import re
from pathlib import Path
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument('--ref', default='5a143095f1163be2be3302e342753abce6f8109e')
args = parser.parse_args()
repo = Path(__file__).resolve().parents[2]
sha = subprocess.check_output(['git', 'rev-parse', '--verify', args.ref + '^{commit}'], cwd=repo, text=True).strip()
source = subprocess.check_output(['git', 'show', sha + ':learn.html'], cwd=repo, text=True)
# Keep the UI mascot replacement reproducible without changing the course source.
source, cat_count = re.subn(
    r'function catSVG\(mood\)\{.*?\n\}(?=\nconst setCat=)',
    '''function catSVG(mood){
  const expression = mood==='good' ? 'good' : mood==='bad' ? 'bad' : 'idle';
  return `<span class="coach-cat coach-cat--${expression}" role="img" aria-label="六六（Leo-Leo）教练"></span>`;
}''',
    source, count=1, flags=re.S)
if cat_count != 1:
    raise SystemExit('Teaching cat source changed; review this adapter.')
nav = '<nav class="study-nav" aria-label="模式"><a class="study-brand" href="index.html">80<span>分</span></a><span class="study-current">学一手</span><a class="learn-link" href="index.html">去打牌 ↗</a></nav>'
replacements = [
    ('<title>80分教学 · 第一单元</title>', '<title>80分 · 学一手</title>'),
    ('</style>\n</head>', '</style>\n<link rel="stylesheet" href="theme.css">\n<link rel="stylesheet" href="learn-theme.css">\n<link rel="stylesheet" href="leo-theme.css">\n<link rel="stylesheet" href="study-layout.css">\n</head>'),
    ("const LS='80fenlearn-';", "const LS='80fen-ui-study-preview-';"),
    ("function drawMap(){\n  let html='';", "function drawMap(){\n  let html=" + repr(nav) + ';'),
    ('<div id="bar"><div id="barIn"></div></div>', '<span class="lesson-position" id="lessonPosition"></span><div id="bar"><div id="barIn"></div></div><a class="learn-link" href="index.html" aria-label="离开练习，去牌桌">打牌</a>'),
    ("function show(p){", "function show(p){\n  $('app').dataset.screen=p;"),
    ("$('barIn').style.width=(qi/L.qs.length*100)+'%';", "$('barIn').style.width=(qi/L.qs.length*100)+'%';\n  $('lessonPosition').textContent=(qi+1)+' / '+L.qs.length;"),
    ('<div id="coach"><span id="face"></span><div id="bub"></div></div>', '<div id="coach"><div class="coach-identity"><span id="face"></span><span>六六</span></div><div id="bub"></div></div>'),
    ('<button class="rnd" id="hintBtn" title="问教练">💡</button>', '<button class="rnd" id="hintBtn" title="问六六" aria-label="问六六，获得提示">提示</button>'),
    ('<div class="big">🐱</div>', '<div class="big leo-avatar happy" role="img" aria-label="六六开心地笑"></div>'),
]
for before, after in replacements:
    if source.count(before) != 1:
        raise SystemExit('Teaching source changed; review this adapter: ' + before[:70])
    source = source.replace(before, after)
source, map_count = re.subn(r'function drawMap\(\)\{.*?\n\}(?=\n\n/\* ---------- 出牌区)', lambda _: (repo/'ui/scripts/study-map.js').read_text().strip(), source, count=1, flags=re.S)
if map_count != 1:
    raise SystemExit('Teaching map source changed; review this adapter.')
source = source.replace('<!doctype html>', '<!doctype html>\n<!-- Teaching style preview; source: ' + sha + '. Course and grading logic preserved. -->', 1)
(repo/'ui/dist/learn.html').write_text(source)
(repo/'ui/dist/learn-source.txt').write_text('Source: ChannonTian/80fen learn.html\nCommit: ' + sha + '\nGenerated by ui/scripts/refresh-learn-preview.py\nLocal changes: shared Leo-Leo theme, responsive practice layout, course map, navigation, title, isolated progress key, coach avatar and accessible name.\nCourse definitions, grading and progression storage preserved.\n')
print('Teaching style preview updated from ' + sha)
